name: eduflix
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.0







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  l: ^4.0.2
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  device_preview: ^1.2.0

  #for locale storage
  shared_preferences: ^2.3.2

  #for state management
  flutter_riverpod: ^2.5.1

  #for rules
  dart_code_metrics_presets: ^2.15.0


  #for date picker
  flutter_neat_and_clean_calendar: ^0.4.14
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1





flutter:

  
  
  
  uses-material-design: true

  
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  
  

  
  

  
  
  
  
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  
  
